export const API_REQ = 'API_REQ';
export const API_REQ_SUCCEEDED = 'API_REQ_SUCCEEDED';
export const API_REQ_FAILED = 'API_REQ_FAILED';

export const API_REQ_DETAIL = 'API_REQ_DETAIL';
export const API_REQ_DETAIL_SUCCEEDED = 'API_REQ_DETAIL_SUCCEEDED';
export const API_REQ_DETAIL_FAILED = 'API_REQ_DETAIL_FAILED';
